### ISSUE TITLE
Dynamic route API throws 404 when running on Layer0

### ISSUE THREAD

**Issue by MalikKadiwar** [rishi-raj-jain/static-medium-isr-in-nuxtjs-with-layer0#8]
Hi Rishi,

Thanks for the quick fix you did for previous issue.

Here I observed new issue, When running the site on layer0(npm run layer0:dev)

**Step 1** : Run the application npm run 0:dev
**Step 2** : One the application started, search something in query search(for ex: inkdrop) and hit search
![image](https://user-images.githubusercontent.com/107252867/173756849-b2683c21-b0d6-4aeb-a014-db9149124695.png)
**Step 3** : our api/.json throws 404
![image](https://user-images.githubusercontent.com/107252867/173757048-9dcba099-2e8d-42ad-8f45-9347e3ad285f.png)

**Comment by rishi-raj-jain** [comment]
Hey, thanks for bringing another quality issue. Just pushed a fix for this. Shall work fine.
